final List<Map<String, dynamic>> corbaListesi = [
  {
    'ad': 'Mercimek Çorbası',
    'tarif':
        'Lokanta usulü tam kıvamında süzme mercimek çorbası için kollarımızı sıvıyoruz! Öncelikle 2 su bardağı kırmızı mercimeği iyice yıkayıp suyunu süzüyoruz. Bir tencerede 2 yemek kaşığı tereyağı ve 1 yemek kaşığı sıvı yağı kızdırıp, yemeklik doğranmış 1 adet orta boy soğanı şeffaflaşana kadar kavuruyoruz. Ardından 1 yemek kaşığı unu ekleyip unun kokusu çıkana kadar (yaklaşık 2 dakika) kavurmaya devam ediyoruz. Şimdi işin sırrına geliyoruz: Küp küp doğranmış 1 adet patates ve 1 adet havucu da ekleyip birkaç tur çeviriyoruz. Yıkadığımız mercimekleri tencereye alıp üzerine 1,5 litre sıcak su (varsa et veya tavuk suyu harika olur) ekliyoruz. Tuz, karabiber ve bir çay kaşığı zerdeçal (o altın sarısı renk için şart!) ilave edip sebzeler yumuşayana kadar orta ateşte pişirmeye bırakıyoruz. Tüm sebzeler piştikten sonra çorbamızı pürüzsüz bir kıvam alana kadar blenderdan geçiriyoruz. Eğer kıvamı çok koyu gelirse biraz daha sıcak su ekleyerek açabilirsiniz. Servis yapmadan hemen önce küçük bir tavada tereyağını kızdırıp üzerine pul biber ve nane ekleyerek yakıyoruz. Çorbayı kaselere paylaştırdıktan sonra bu nefis sosu üzerinde gezdiriyoruz. Yanına bir dilim limon ve kıtır ekmekle servis edilince tadından yenmez!',
    'malzemeler': [
      '2 su bardağı kırmızı mercimek',
      '2 yemek kaşığı tereyağı',
      '1 yemek kaşığı sıvı yağ',
      '1 adet orta boy soğan',
      '1 yemek kaşığı un',
      '1 adet patates',
      '1 adet havuç',
      '1,5 litre su (veya et suyu)',
      'Tuz, karabiber, zerdeçal',
      'Pul biber ve nane (sos için)',
    ],
    'hazirlasuresi': '10 dk',
    'pisirmesuresi': '35 dk',
    'zorluk': 'Orta',
    'kisisayisi': '4-6',
    'kalori': '120 kcal',
  },
  {
    'ad': 'Tarhana Çorbası',
    'tarif':
        'Tarhana, Anadolu\'nun geleneksel hazırlanmış kuru bir ürünüdür. Soğuk suda eritilen tarhana, kaynayan suya yavaşça eklenerek homojen bir kıvam elde edilir. Kısık ateşte 15 dakika kadar pişirildikten sonra, tereyağında kızartılmış pul biber ile servis edilir. Bu basit ama doyurucu çorba, her mevsimde tüketilir.',
    'malzemeler': [
      '3 yemek kaşığı tarhana',
      '1 litre su',
      '2 yemek kaşığı tereyağı',
      '1 çay kaşığı pul biber',
      'Tuz, karabiber',
    ],
    'hazirlasuresi': '5 dk',
    'pisirmesuresi': '15 dk',
    'zorluk': 'Kolay',
    'kisisayisi': '3-4',
    'kalori': '95 kcal',
  },
  {
    'ad': 'Tavuk Suyu Çorbası',
    'tarif':
        'Tavuk suyu çorbası, haşlanmış tavuktan yapılmış sağlıklı ve besleyici bir çorbadır. Tavuk etleri haşlandıktan sonra didiklenerek, çorba suyu içine katılır. Pirinç ve sebzelerle zenginleştirilen bu çorba, limon ve nane ile tamamlanır. Özellikle hastalık dönemlerinde besleyici bir seçim olarak tüketilir.',
    'malzemeler': [
      '500 gram tavuk göğsü',
      '1 litre su',
      '1/2 su bardağı pirinç',
      '1 adet havuç',
      '2 adet patates',
      '1 adet soğan',
      'Limon, tuz, karabiber',
      'Taze nane (servis için)',
    ],
    'hazirlasuresi': '15 dk',
    'pisirmesuresi': '30 dk',
    'zorluk': 'Kolay',
    'kisisayisi': '4-5',
    'kalori': '140 kcal',
  },
  {
    'ad': 'Düğün Çorbası',
    'tarif':
        'Düğün çorbası, özel günlerde yapılan ve yoğurt terbiyesiyle hazırlanan lezzetli bir çorbadır. Kuzu etinden hazırlanan et veya sebze suyu, yoğurt ve yumurta karışımıyla bağlanır. Tavada kızartılan pul biber ve nane ile sunulan bu çorba, şerefe içilir ve törensel bir anlamı vardır.',
    'malzemeler': [
      '500 gram kuzu eti',
      '1 litre su',
      '500 gram süzme yoğurt',
      '2 adet yumurta (sarısı)',
      '2 yemek kaşığı un',
      '2 yemek kaşığı tereyağı',
      'Pul biber, nane',
      'Limon suyu, tuz, karabiber',
    ],
    'hazirlasuresi': '20 dk',
    'pisirmesuresi': '40 dk',
    'zorluk': 'Zor',
    'kisisayisi': '6-8',
    'kalori': '155 kcal',
  },
  {
    'ad': 'Yoğurtlu Çorba',
    'tarif':
        'Yoğurtlu çorba, pirinçle yapılan besleyici ve hafif bir çorbadır. Pirinçler haşlandıktan sonra, taze yoğurt ve sebzeler eklenir. Tuz ve baharat ile tatlandırılan bu çorba, sıcak servisi yapılır. Taze nane yaprakları ve ceviz parçaları ile garnır edilerek sunulur.',
    'malzemeler': [
      '1/2 su bardağı pirinç',
      '1 litre tavuk suyu',
      '500 gram süzme yoğurt',
      '2 adet yumurta',
      '2 yemek kaşığı un',
      '1 yemek kaşığı tereyağı',
      'Taze nane, dill',
      'Tuz, karabiber, sumak',
    ],
    'hazirlasuresi': '10 dk',
    'pisirmesuresi': '25 dk',
    'zorluk': 'Kolay',
    'kisisayisi': '4-6',
    'kalori': '130 kcal',
  },
];

final List<Map<String, dynamic>> anaYemekListesi = [
  {
    'ad': 'Karnıyarık',
    'tarif':
        'Karnıyarık, Türk mutfağının en meşhur yemeklerinden biridir. Uzun patlıcanlar çöpte kızartılıp içleri boş bırakılırken, diğer taraftan taze kıyma, soğan ve domates ile hazırlanan harç yapılır. Boş patlıcanlar bu kıymalı harçla doldurulur, ardından fırında poğaça-çomlek ateşinde pişirilir. Üzerine domates sosu dökülüp servisi yapılır. Yanında pirinç pilavı ve yoğurt ile sunulur.',
    'malzemeler': [
      '6 adet uzun patlıcan',
      '500 gram kıyma',
      '2 adet orta boy soğan',
      '3 adet domates',
      '1/2 su bardağı ıspanak',
      '1/4 çay kaşığı tarçın',
      'Sıvı yağ, tuz, karabiber',
      'Domates sosu (1 su bardağı)',
    ],
    'hazirlasuresi': '25 dk',
    'pisirmesuresi': '40 dk',
    'zorluk': 'Orta',
    'kisisayisi': '4-5',
    'kalori': '280 kcal',
  },
  {
    'ad': 'Kayseri Mantısı',
    'tarif':
        'Kayseri mantısı, harç yapılan minik hamur parçalarının özel bir şekilde yapıldığı ve yoğurtla servis edilen bir yemektir. İnce açılan hamur karesel parçalar halinde kesilip taze kıyma ve baharat ile doldurulur. Haşlamada dikkat edilmeli, açılan hamurlar bir tabaka halinde yapıştırılmış şekilde kaynayan suya eklenir. Haşlandıktan sonra süzülen mantılar, üzerine kızdırılan kırmızı biber ve nane saçılan yoğurtla sunulur.',
    'malzemeler': [
      '3 su bardağı un',
      '1 adet yumurta',
      'Tuz, su (hamur için)',
      '500 gram kıyma',
      '1 adet soğan',
      '1 çay kaşığı pul biber',
      '1 kg süzme yoğurt',
      'Nane, kırmızı biber, tereyağı',
    ],
    'hazirlasuresi': '45 dk',
    'pisirmesuresi': '20 dk',
    'zorluk': 'Zor',
    'kisisayisi': '6-8',
    'kalori': '320 kcal',
  },
  {
    'ad': 'Kuru Fasulye',
    'tarif':
        'Kuru fasulye, Türk mutfağının en besleyici ve doldurici yemeklerinden biridir. Gece önceden bekletilen kuru fasulyelerin suyu değiştirilip taze suyla haşlanmasıyla başlanır. Eti küçük parçalara doğranan dana etleri kavurma yapılıp içine katılır. Ardından domates salçası, soğan, sarımsak ve baharatlar ilave edilir. Düşük ateşte 2-3 saat pişirilmesi sonucunda lezzetli bir yemek hazır olur.',
    'malzemeler': [
      '500 gram kuru fasulye',
      '400 gram dana eti',
      '3 yemek kaşığı domates salçası',
      '2 adet soğan',
      '3 diş sarımsak',
      '1/2 çay kaşığı pul biber',
      'Sıvı yağ, tuz, karabiber, bay yaprakları',
    ],
    'hazirlasuresi': '20 dk',
    'pisirmesuresi': '120 dk',
    'zorluk': 'Kolay',
    'kisisayisi': '6-8',
    'kalori': '240 kcal',
  },
  {
    'ad': 'İçli Köfte',
    'tarif':
        'İçli köfte, bulgurdan yapılan dışı ve içinde kıyma olan harçla doldurulmuş bir yemektir. Bulgur, tuz ve baharatlarla ıslatılıp yoğrulur. Ayrıca kıyma, soğan, fistık ve sumaktan yapılan harç hazırlanır. Bulgur hamurundan oval şekiller yapılıp içleri boş bırakılır, bu boşluklara kıyma harcı doldurulur. Sıcak yağda kızartılarak sarı rengini alana kadar pişirilir.',
    'malzemeler': [
      '2 su bardağı bulgur',
      '1 litre su (bulgur için)',
      '500 gram kıyma (dış)',
      '300 gram kıyma (iç)',
      '2 adet soğan',
      '1/2 su bardağı fistık',
      '1 çay kaşığı sumak',
      'Tuz, karabiber, kimyon, sıvı yağ',
    ],
    'hazirlasuresi': '30 dk',
    'pisirmesuresi': '20 dk',
    'zorluk': 'Zor',
    'kisisayisi': '5-6',
    'kalori': '350 kcal',
  },
  {
    'ad': 'Fırın Balık',
    'tarif':
        'Fırın balığı, taze balık ve sebzelerin zeytinyağıyla fırında pişirildiği sağlıklı bir yemektir. Temizlenen balık, içi ve dışı tuz, karabiber ile baharat yapılır. Fırına alınmış bir tepsiye domates, soğan, limon dilimleri ve fesleğen yayılır. Balık bu sebzelerin üzerine konur, üzerine daha fazla sebze ve limon konarak zeytinyağı dökülür. 180 derece fırında yaklaşık 25-30 dakika pişirilir.',
    'malzemeler': [
      '1 adet 1 kg balık (çipura, levrek vs)',
      '3 adet domates',
      '2 adet soğan',
      '1 adet limon',
      '1/2 su bardağı zeytinyağı',
      'Taze fesleğen, dill',
      'Tuz, karabiber, pul biber',
    ],
    'hazirlasuresi': '15 dk',
    'pisirmesuresi': '30 mk',
    'zorluk': 'Orta',
    'kisisayisi': '4-5',
    'kalori': '220 kcal',
  },
];

final List<Map<String, dynamic>> tatliListesi = [
  {
    'ad': 'Kadayıf',
    'tarif':
        'Kadayıf, tel tatlısı olarak da bilinen ve ince teller halinde hamurdan yapılan bir tatlıdır. Hazır kadayıf, tereyağı ile harmanlanan ve üzerine yer fıstığı veya antep fıstığı serpilen bir tepsiye yayılır. 180 derece fırında kızarıncaya kadar pişirilir. Tatlı fırından çıkarıldığında hemen üzerine sıcak şerbeti dökülür. Bu işlem, tatlının şerbeti içinde iyi bir şekilde emebilmesini sağlar. Üst tarafına fistik ve ceviz dekorasyonu yapılır.',
    'malzemeler': [
      '500 gram hazır kadayıf',
      '300 gram tereyağı',
      '1 su bardağı yer fıstığı',
      '1 su bardağı antep fıstığı',
      '3 su bardağı şeker',
      '1,5 su bardağı su',
      '1/2 limon suyu',
      '5-6 adet çiçek (dekorasyon)',
    ],
    'hazirlasuresi': '15 dk',
    'pisirmesuresi': '30 mk',
    'zorluk': 'Orta',
    'kisisayisi': '8-10',
    'kalori': '350 kcal',
  },
  {
    'ad': 'Baklava',
    'tarif':
        'Baklava, Türk mutfağının en ünlü tatlısıdır. İnce yufkalar bir tepsiye katman halinde yerleştirilir, her iki yufka arasına tereyağı sürülür. Ceviz veya fistik parçaları her katman arasına serpilir. Yufkalar bittikten sonra baklava elmas veya kare şekiller halinde kesilerek fırına alınır. Yaklaşık 35-40 dakika 180 derece fırında pişirilmesi sonucunda altı açık rengini alır. Fırından çıkarıldığında hemen üzerine soğuk veya ılık şerbeti dökülür.',
    'malzemeler': [
      '1 paket yufka',
      '300 gram tereyağı (eritilmiş)',
      '2 su bardağı ceviz',
      '1 su bardağı fistik',
      '1 çay kaşığı tarçın',
      '4 su bardağı şeker',
      '2 su bardağı su',
      '1 limon suyu',
    ],
    'hazirlasuresi': '30 mk',
    'pisirmesuresi': '40 mk',
    'zorluk': 'Zor',
    'kisisayisi': '10-12',
    'kalori': '380 kcal',
  },
  {
    'ad': 'Fırın Sütlaç',
    'tarif':
        'Fırın sütlaçı, pirinç ve sütten yapılan besleyici ve yumuşak bir tatlıdır. Pirinçler iyice yıkandıktan sonra bir tencereye alınıp su ile biraz haşlanır. Yumuşayan pirinçlere, şeker ve süt ilave edilir. Bu karışım, kıtar kıtar dönerken mısır nişastası hamuru eklenip karıştırılır. Süt karışımı kalınlaştığında, önceden tereyağı ile sürülmüş kaplara paylaştırılır. Fırında ılık bir şekilde pişirilen sütlaç, üzerine tarçın serpilip soğumaya bırakılır.',
    'malzemeler': [
      '1 su bardağı pirinç',
      '1 litre süt',
      '1/2 su bardağı şeker',
      '3 yemek kaşığı mısır nişastası',
      '2 yemek kaşığı su',
      '2 yemek kaşığı tereyağı',
      '1 çay kaşığı tarçın (dekorasyon)',
    ],
    'hazirlasuresi': '20 dk',
    'pisirmesuresi': '35 mk',
    'zorluk': 'Kolay',
    'kisisayisi': '6-8',
    'kalori': '220 kcal',
  },
  {
    'ad': 'Kazandibi',
    'tarif':
        'Kazandibi, muhallebi tatlısının altının tepside hafifçe yakılarak hazırlandığı bir tatlıdır. Başta muhallebi hazırlanır: süt, şeker ve mısır nişastası karıştırılarak pişirilir. Muhallebi kalınlaştığında, üzerine toz fistik serpilir. Muhallebi, önceden tereyağı ile sürülmüş geniş ve sı tepsiyle aktarılır. Muhallebi soğuduktan sonra, tepsiniz altında biraz yakarsak altı hafif kızararak lezzetli bir kabuk oluşur. Bu lezzet taze servis edilir.',
    'malzemeler': [
      '1 litre süt',
      '1/2 su bardağı şeker',
      '4 yemek kaşığı mısır nişastası',
      '3 yemek kaşığı su',
      '2 yemek kaşığı tereyağı',
      '1 su bardağı toz fistik',
      '1 çay kaşığı vanilya',
    ],
    'hazirlasuresi': '15 mk',
    'pisirmesuresi': '25 mk',
    'zorluk': 'Orta',
    'kisisayisi': '8-10',
    'kalori': '280 kcal',
  },
  {
    'ad': 'Maraş Dondurması',
    'tarif':
        'Maraş dondurması, bol sahlep ve keçi sütü kullanılarak yapılan ve türnası ile dövülerek katılaştırılan özel bir dondurmadır. Dondurma, klasik dondurmadan farklı olarak dondurulurken özel makinalarla ısıtılan bir taşta dövülür ve buna sahilep (orchid unu) karıştırılır. Bu işlem, dondurmanın kalınlığını ve özel tekstürünü oluşturur. Kahvaltı veya tatlı olarak sunulan bu lezzet, bazı yerlerde tel rölatası ve fıstıkla servis edilir.',
    'malzemeler': [
      '1 litre süt',
      '1/2 su bardağı şeker',
      '3 yemek kaşığı sahilep (orchid unu)',
      '1/4 su bardağı keçi sütü (varsa)',
      '1 çay kaşığı vanilya',
      '1 su bardağı toz fistik',
      '1/2 su bardağı çikolata (isteğe bağlı)',
    ],
    'hazirlasuresi': '20 mk',
    'pisirmesuresi': '360 mk (donma süresi)',
    'zorluk': 'Zor',
    'kisisayisi': '6-8',
    'kalori': '180 kcal',
  },
];

final List<Map<String, dynamic>> viralCorbaListesi = [
  {
    'ad': 'Dalgona Kahvesi',
    'tarif':
        'Dalgona kahvesi, TikTok ve Instagram\'da viral olan ve 1 milyardan fazla görünüş alan basit bir kahve tarifidir. Instant kahve, şeker ve su eşit miktarda karıştırılıp elektrikli mikserle çırpılır. Yaklaşık 5-10 dakika çırpıldığında koyu kahverengi, akıcı bir krem oluşur. Bardağa soğuk veya sıcak su dökülüp üzerine bu köpüklü kahve kıvamı eklenir. Üzerine kakao tozu ve çikolatanın servis edilir. İdeal sıcaklıkta sunulan bu kahve, sosyal medyada viral olmuştur.',
    'malzemeler': [
      '2 çorba kaşığı instant kahve',
      '2 çorba kaşığı şeker',
      '2 çorba kaşığı sıcak su',
      '1 su bardağı soğuk veya sıcak süt',
      'Kakao tozu (dekorasyon)',
      'Buz (isteğe bağlı)',
    ],
    'hazirlasuresi': '15 dk',
    'pisirmesuresi': '0 dk',
    'zorluk': 'Kolay',
    'kisisayisi': '1-2',
    'kalori': '80 kcal',
    'viral': true,
  },
  {
    'ad': 'Açılı Çikolata Küresi',
    'tarif':
        'Açılı çikolata küresi, Instagram\'da viral olan ve orta sınıfta 2 milyondan fazla beğeni alan bir tatlıdır. Bazlama hamuru ve çikolata ile hazırlanan bu tarif, çok kolay ve hızlı yapılır. Hazır bazlama hamuru açılıp içi çikolata ve marshmallow ile doldurulur. Fırında pişirildiğinde çikolata erimiş şekilde kurşun açılır. Sıcak çikolata çeşmesi gibi akıp gözle görülür. Bu anı video çekmek için ideal olan tarif, sosyal medyada çok paylaşılır.',
    'malzemeler': [
      '2 paket hazır bazlama',
      '100 gram çikolata (parça)',
      '50 gram marshmallow',
      '1 yumurta (fırça için)',
      'Şeker (üst için)',
    ],
    'hazirlasuresi': '10 dk',
    'pisirmesuresi': '25 dk',
    'zorluk': 'Çok Kolay',
    'kisisayisi': '2-3',
    'kalori': '280 kcal',
    'viral': true,
  },
  {
    'ad': 'Nutella Cheesecake',
    'tarif':
        '3 malzeme ile yapılan Nutella cheesecake, YouTube\'da viral olan bir tatlıdır. Sadece cream cheese, Nutella ve yumurta ile hazırlanan bu tatlı, şaşırtıcı ölçüde lezzetli çıkar. Tüm malzemeler karıştırıldıktan sonra hazır bastırma konursa yapılmış tepsiye dökülür ve fırında pişirilir. Soğuduktan sonra bir çikolataya sahip olur. Diş doku ve tadı profesyonel pastane kalitesindedir.',
    'malzemeler': [
      '200 gram cream cheese',
      '200 gram Nutella',
      '2 adet yumurta',
      '150 gram basırma bisküvisi (taban)',
      '100 gram tereyağı (taban)',
    ],
    'hazirlasuresi': '15 dk',
    'pisirmesuresi': '30 mk',
    'zorluk': 'Çok Kolay',
    'kisisayisi': '6-8',
    'kalori': '350 kcal',
    'viral': true,
  },
];

final List<Map<String, dynamic>> viralAnaYemekListesi = [
  {
    'ad': 'Sucuk Sarıyer',
    'tarif':
        'Sucuk Sarıyer, Istanbul\'un ünlü sokak yemegi olup, internet\'te viral olmuş bir yemektir. Kızarılmış sucuk, erimiş peynirin üzerine konup kepekli ekmek ile servis edilir. Bazen sucuk ve peynir bir tost makinasında yan yana şekillendirilir ve kıtır kıtır bir dış katmanı olur. Çok basit ama çok etkili bir kombinasyon olan bu yemek, hızlı ve ucuz yapılır.',
    'malzemeler': [
      '4 dilim sucuk',
      '100 gram kaşar peyniri',
      '4 dilim kepekli ekmek',
      '1 yemek kaşığı tereyağı',
      'Tuz, karabiber',
    ],
    'hazirlasuresi': '5 dk',
    'pisirmesuresi': '10 mk',
    'zorluk': 'Çok Kolay',
    'kisisayisi': '2',
    'kalori': '320 kcal',
    'viral': true,
  },
  {
    'ad': 'Kek Gömlekli Hamburger',
    'tarif':
        'Kek gömlekli hamburger, sosyal medyada viral olan ve milyonlarca kez izlenen bir tarifidir. Normal hamburger ekmeği yerine ince kek dilimleri kullanılır. Arada hamburger köfteleri, peynir ve diğer malzemeler konur. Sonra kek gömlekli hamburger tamamı sos ile ballandırılıp servisi yapılır. Tatlı ve tuzlu karışımı ilginç bir lezzet kombinasyonu oluşturur.',
    'malzemeler': [
      '2 dilim hafif tatlı kek',
      '200 gram burger köftesi',
      '1 dilim peynir',
      '2 dilim domates',
      '2 yaprak marul',
      'Ketchup, mayonez, hardal',
    ],
    'hazirlasuresi': '10 mk',
    'pisirmesuresi': '15 mk',
    'zorluk': 'Kolay',
    'kisisayisi': '1-2',
    'kalori': '450 kcal',
    'viral': true,
  },
];

final List<Map<String, dynamic>> viralTatliListesi = [
  {
    'ad': 'İnstagram Pasta',
    'tarif':
        'İnstagram pastası veya "Aesthetic Cake", sosyal medyada paylaşılması için tasarlanmış, çok güzel görünen bir pastadır. Katmanlardan oluşan bu pasta, beslenme ve görsel olarak çarpıcı bir kombinasyon sunuyor. Kek tabanları ve farklı renkteki kremleri şeffaf cam bir kapta servis edilir, böylelikle katmanları görünür. Üzerine taze meyveler ve yenilebilir çiçekler konur.',
    'malzemeler': [
      '500 gram şeker',
      '4 adet yumurta',
      '300 gram un',
      '200 ml süt',
      '300 gram tereyağı',
      'Gıda boyası (çeşitli renkler)',
      'Taze meyveler ve çiçekler (dekorasyon)',
    ],
    'hazirlasuresi': '30 mk',
    'pisirmesuresi': '40 mk',
    'zorluk': 'Orta',
    'kisisayisi': '8-10',
    'kalori': '280 kcal',
    'viral': true,
  },
  {
    'ad': 'Viral Çikolata Topları',
    'tarif':
        'Viral çikolata topları, TikTok\'ta 500 milyon görünüşten fazla olan bir tatlıdır. Oreo bisküvi ve cream cheese ile yapılan bu tatlı, çok hızlı ve kolay bir şekilde hazırlanır. Oreo bisküvileri blenderdan geçirilerek toz haline getirilir, cream cheese ile karıştırılır ve top şeklinde biçimlendirilir. Sonra erimiş çikolataya batırılıp donma kabı bırakılır. Çok güzel görünen ve sezilmiş lezzet bir tatlıdır.',
    'malzemeler': [
      '20 adet Oreo bisküvi',
      '200 gram cream cheese',
      '200 gram çikolata (eritilmiş)',
      '1 yemek kaşığı kokonut yağı',
      'Fındık, ceviz, kokus (topping)',
    ],
    'hazirlasuresi': '20 mk',
    'pisirmesuresi': '180 mk (donma)',
    'zorluk': 'Çok Kolay',
    'kisisayisi': '8-10',
    'kalori': '180 kcal',
    'viral': true,
  },
];
